runtime: nodejs14

instance_class: F2

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DATABASE_NAME: "strapi"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "GCloudStrapi21"
  INSTANCE_CONNECTION_NAME: "strapi-accountability-308920:us-central1:strapi-db"

beta_settings:
  cloud_sql_instances: "strapi-accountability-308920:us-central1:strapi-db"
